trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bicep/**

pr:
  branches:
    include:
      - main

variables:
  azureServiceConnection: 'AZURE-SERVICE-CONNECTION'
  resourceGroupName: 'rg-platform-dev'
  location: 'westeurope'
  templateFile: 'bicep/platform/main.bicep'
  parametersFile: 'bicep/platform/parameters.bicepparam'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Validate
  displayName: 'Validate Bicep templates'
  jobs:
  - job: BicepValidate
    steps:
    - task: AzureCLI@2
      displayName: 'Bicep build & lint'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az bicep version
          az bicep build --file $(templateFile)

- stage: Deploy
  displayName: 'Deploy Azure Platform (Bicep)'
  dependsOn: Validate
  condition: succeeded()
  jobs:
  - job: DeployPlatform
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Bicep to Azure'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az group create \
            --name $(resourceGroupName) \
            --location $(location)

          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file $(templateFile) \
            --parameters $(parametersFile)
